# Making sure dependencies are kept up-to-date
version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/app"
    schedule:
      interval: "daily"
  
  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "daily"