# permissions for end users to view mlflows.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: mlflow-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: mlflow-operator
    app.kubernetes.io/part-of: mlflow-operator
    app.kubernetes.io/managed-by: kustomize
  name: mlflow-viewer-role
rules:
- apiGroups:
  - mlflow.trendyol.com
  resources:
  - mlflows
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mlflow.trendyol.com
  resources:
  - mlflows/status
  verbs:
  - get
