---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - mlflow.server.trendyol.com
  resources:
  - mlflowserverconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mlflow.server.trendyol.com
  resources:
  - mlflowserverconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - mlflow.server.trendyol.com
  resources:
  - mlflowserverconfigs/status
  verbs:
  - get
  - patch
  - update
