
publications:
  - url: https://nuget.org/packages/LaunchDarkly.Logging.NLog
    description: NuGet

circleci:
  windows:
    context: org-global

template:
  name: dotnet-windows
  env:
    LD_RELEASE_TEST_TARGET_FRAMEWORK: netcoreapp2.1
    LD_RELEASE_DOCS_TARGET_FRAMEWORK: netstandard2.0

documentation:
  title: LaunchDarkly Logging API for .NET - NLog Adapter
  githubPages: true
