site_name: iCloud Photos Sync
site_url: https://icloud-photos-sync.steilerdev.de
site_description: Documentation for icloud-photos-sync by steilerDev
site_author: Frank Steiler
copyright: steilerDev
repo_url: https://github.com/steilerDev/icloud-photos-sync
edit_uri: ""
nav:
  - 'Home': README.md
  - 'User Guides': 
    - 'CLI Reference': user-guides/cli.md
    - 'NPM User Guide': user-guides/npm.md
    - 'Docker User Guide': user-guides/docker.md
    - 'Error & Crash Reporting': user-guides/telemetry.md
  - 'Development Ressources':
    - 'Milestone Plan': https://github.com/steilerDev/icloud-photos-sync/milestones
    - 'Test Environment': dev/test-environment.md
    - 'Motivation': dev/motivation.md
    - 'API': dev/api.md
    - 'Local File Structure': dev/local-file-structure.md
    - 'TypeDoc Code Documentation': https://github.com/steilerDev/icloud-photos-sync/wiki/Exports
    - 'Coverage': dev/coverage.md
  - 'Changelog': CHANGELOG.md

theme:
  name: material
  logo: assets/icloud-photos-sync.svg
  favicon: assets/icloud-photos-sync.svg
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep-orange
      accent: deep-orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep-orange
      accent: deep-orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
dev_addr: 0.0.0.0:8000
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
plugins:
  - search:
      prebuild_index: true