name: API Test
# This workflow continously runs the API Tests for this projects, to validate that the undocumented API used does not change
# Should the provided token expire, the job will wait for a refresh of the token or timeout

on:
  schedule:
    - cron: '0 7,16,19 * * *'
  workflow_dispatch:

env:
  PKG_NAME: icloud-photos-sync
  NODE_VERSION: 18
  APPLE_ID_USER: ${{ secrets.TEST_APPLE_ID_USER }}
  APPLE_ID_PWD: ${{ secrets.TEST_APPLE_ID_PWD }}
  #TRUST_TOKEN: ${{ secrets.TEST_TRUST_TOKEN }}
  PORT: 8080
  LOG_LEVEL: debug
  LOG_TO_CLI: true

jobs:
  run-test:
    name: Build Project & Start SSH
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Build & Install
      run: |
        npm run clean && \
        npm install && \
        npm run build
      working-directory: rootfs/opt/icloud-photos-sync/
    - name: Install
      run: |
        npm link && \
        chmod +x~/work/icloud-photos-sync/icloud-photos-sync/rootfs/root/enter_mfa.sh && \
        ln -s ~/work/icloud-photos-sync/icloud-photos-sync/rootfs/root/enter_mfa.sh /usr/local/bin/enter_mfa && \
        chmod +x ~/work/icloud-photos-sync/icloud-photos-sync/rootfs/root/resend_mfa.sh && \
        ln -s ~/work/icloud-photos-sync/icloud-photos-sync/rootfs/root/resend_mfa.sh /usr/local/bin/resend_mfa
      working-directory: rootfs/opt/icloud-photos-sync/
    - name: Check MFA Token
      run: |
        icloud-photos-sync token
      env:
        FAIL_ON_MFA: true
    - name: Acquire token
      if: failure() && ${{ github.event_name == 'workflow_dispatch' }}
      uses: lhotari/action-upterm@v1
      with:
        limit-access-to-users: steilerDev
        upterm-server: ssh://uptermd.upterm.dev
    - name: Run API Test
      run: |
        npm run test-api
      working-directory: rootfs/opt/icloud-photos-sync/