name: API Test
# This workflow continously runs the API Tests for this projects, to validate that the undocumented API used does not change
# Should the provided token expire, the job will wait for a refresh of the token or timeout

on: [workflow_dispatch]

env:
  PKG_NAME: icloud-photos-sync
  NODE_VERSION: 18

jobs:
  run-test:
    name: Build Project & Start SSH
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Build
      run: |
        npm run clean && \
        npm install && \
        npm run build
      working-directory: rootfs/opt/icloud-photos-sync/
    - name: Setup upterm session
      uses: lhotari/action-upterm@v1
      with:
        limit-access-to-users: 'steilerDev'
        upterm-server: ssh://uptermd.upterm.dev:22