name: API Test
# This workflow continously runs the API Tests for this projects, to validate that the undocumented API used does not change
# Should the provided token expire, the job will wait for a refresh of the token or timeout

on: [workflow_dispatch]

env:
  PKG_NAME: icloud-photos-sync
  NODE_VERSION: 18
  APPLE_ID_USER: ${{ secrets.TEST_APPLE_ID_USER }}
  APPLE_ID_PWD: ${{ secrets.TEST_APPLE_ID_PWD }}
  TRUST_TOKEN: ${{ secrets.TEST_TRUST_TOKEN }}
  PORT: 8080
  LOG_LEVEL: debug
  LOG_TO_CLI: true

jobs:
  run-test:
    name: Build Project & Start SSH
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Build & Install
      run: |
        npm run clean && \
        npm install && \
        npm run build && \
        npm link
      working-directory: rootfs/opt/icloud-photos-sync/
    - name: Check MFA Token
      run: |
        icloud-photos-sync token
      env:
        FAIL_ON_MFA: true
    - name: Acquire token
      if: failure()
      uses: lhotari/action-upterm@v1
      with:
        limit-access-to-users: 'steilerDev'
    - name: Run API Test
      run: |
        npm run test-api
      working-directory: rootfs/opt/icloud-photos-sync/