name: Build & Publish

on: [push, pull_request]

env:
  PKG_NAME: icloud-photos-sync
  NODE_VERSION: 17

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install dependencies & build app
      run: |
        cd rootfs/opt/icloud-photos-sync/ && \
        npm install && \
        npm run test && \
        npm run build
    - name: Prepare assets
      run: tar -C ./rootfs -czf ./rootfs.tar.gz ./
    - name: Upload build
      uses: actions/upload-artifact@v2
      with:
        name: rootfs
        path: ./rootfs.tar.gz
  
  publish-docker-dev:
    name: Publish Project to steilerGroup-Docker
    needs: build
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Download build
      uses: actions/download-artifact@v2
      with:
        name: rootfs
    - name: Login to Docker Registry
      run: docker login ${{secrets.DOCKER_DEV_HOST}} -u ${{secrets.DOCKER_DEV_USERNAME}} -p ${{secrets.DOCKER_DEV_PWD}}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_DEV_HOST}}/$PKG_NAME:latest
    - name: Push the Docker image
      run: docker push ${{secrets.DOCKER_DEV_HOST}}/$PKG_NAME:latest

  publish-docker-prod:
    name: Publish Project to Docker
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Download build
      uses: actions/download-artifact@v2
      with:
        name: rootfs
    - name: Login to Docker Registry
      run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PWD}}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $PKG_NAME
    - name: get-npm-version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@master
      with:
        path: rootfs/opt/icloud-photos-sync
    - name: Tag the Docker image
      run: |
        docker image tag $PKG_NAME ${{secrets.DOCKER_USERNAME}}/$PKG_NAME:latest && \
        docker image tag $PKG_NAME ${{secrets.DOCKER_USERNAME}}/$PKG_NAME:${{ steps.package-version.outputs.current-version}} && \
        docker image ls
    - name: Push the Docker image
      run: docker image push --all-tags ${{secrets.DOCKER_USERNAME}}/$PKG_NAME
    - name: Update Docker Hub Description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PWD }}
        repository: ${{secrets.DOCKER_USERNAME}}/$PKG_NAME
        readme-filepath: ./README.md

  publish-npm:
    name: Publish Project to npm
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install dependencies
      run: |
        cp README.md rootfs/opt/icloud-photos-sync/ && \
        cd rootfs/opt/icloud-photos-sync/ && \
        npm install
    - uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        package: rootfs/opt/icloud-photos-sync/package.json
