name: Build, Test & Scan
# This reusable workflow will test, build and scan the application. All build assets will be packaged and uploaded
# This action is also run, in order to validate, that Pull Requests are functional
# When this workflow is triggered due to a push to dev, testing & code scanning will be skipped/fast tracked
#
# Creates the following artifacts:
#  - docker-artifacts (Docker RootFS + Dockerfile)
#  - npm-artifacts (NPM Upload)
#  - doc-artifacts (Documentation for GH Wiki)
#  - changelog (File containing changelog description)

on:
  workflow_call:
  pull_request:
  push:
    branches:
      - '!main'
      - '!dev'

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: ${{ secrets.NODE_VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
      - name: Build app
        run: |
          npm run clean
          npm install
          npm run build
          cp ../../../README.md ../../../CHANGELOG.md ../../../LICENSE ./
        working-directory: rootfs/opt/icloud-photos-sync/
      - name: Upload npm artifacts
        uses: actions/upload-artifact@v3
        with:
          name: npm-artifacts
          path: |
            ./rootfs/opt/icloud-photos-sync/README.md
            ./rootfs/opt/icloud-photos-sync/CHANGELOG.md
            ./rootfs/opt/icloud-photos-sync/LICENSE
            ./rootfs/opt/icloud-photos-sync/package.json
            ./rootfs/opt/icloud-photos-sync/bin/
      - name: Build doc artifacts
        run: npm run docs
        working-directory: rootfs/opt/icloud-photos-sync/
      - name: Upload doc artifacts
        uses: actions/upload-artifact@v3
        with:
          name: doc-artifacts
          path: |
            ./rootfs/opt/icloud-photos-sync/README.md
            ./rootfs/opt/icloud-photos-sync/CHANGELOG.md
            ./rootfs/opt/icloud-photos-sync/LICENSE
            ./rootfs/opt/icloud-photos-sync/docs/
      - name: Build docker artifacts
        run: |
          # Cleaning unecessary files to slim artifacts
          rm -rf ./rootfs/opt/icloud-photos-sync/docs \
                 ./rootfs/opt/icloud-photos-sync/node_modules \
                 ./rootfs/opt/icloud-photos-sync/src \
                 ./rootfs/opt/icloud-photos-sync/test \
                 ./rootfs/opt/icloud-photos-sync/eslint.config.json \
                 ./rootfs/opt/icloud-photos-sync/jest.config.json \
                 ./rootfs/opt/icloud-photos-sync/tsconfig.json

          # Packaging assets
          tar -C ./rootfs -czf ./rootfs.tar.gz ./

          # Actually building
          docker build . --file Dockerfile --tag ${{ github.event.repository.name }}
          docker save ${{ github.event.repository.name }} | gzip > ./docker-image.tar.gz
      - name: Upload docker artifacts
        uses: actions/upload-artifact@v3
        with:
          name: docker-artifacts
          path: |
            ./README.md
            ./CHANGELOG.md
            ./LICENSE
            ./docker-image.tar.gz
      - name: Build changelog artifact
        run: |
          START_LINE=$(grep -n -m 1 -E '^##' CHANGELOG.md | grep -Eo '^[0-9]+')
          ((START_LINE++))
          END_LINE=$(grep -n -m 2 -E '^##' CHANGELOG.md | tail -n 1 | grep -Eo '^[0-9]+')
          LENGTH=$(( END_LINE - START_LINE ))
          tail -n +$START_LINE CHANGELOG.md | head -n $LENGTH > CHANGELOG.latest.md
      - name: Upload changelog artifact
        uses: actions/upload-artifact@v3
        with:
          name: changelog
          path: ./CHANGELOG.latest.md

  test:
    name: Test Project
    strategy:
      matrix:
        os: ${{ fromJSON(github.ref == 'refs/heads/dev' && '["ubuntu-latest"]' || '["ubuntu-latest", "macos-latest"]') }} # Skipping macOS on 'dev' branch, due to slow performance
    runs-on: ${{ matrix.os }}
    env:
      NODE_OPTIONS: --experimental-vm-modules # Needed for JEST / ESM compatibility
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: $NODE_VERSION
        env:
          NODE_VERSION: ${{ secrets.NODE_VERSION }}
      - name: Clean
        run: npm run clean
        working-directory: rootfs/opt/icloud-photos-sync/
      - name: Install
        run: npm install
        working-directory: rootfs/opt/icloud-photos-sync/
      - name: Test
        run: npm run test
        working-directory: rootfs/opt/icloud-photos-sync/

  scan:
    name: Perform Code Scan
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/dev' # Skip this on dev branch
    permissions:
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2