name: Development Release
# This workflow will run on every push against the main or dev branch
# If the app builds and passes tests, it will release to the development channel (Docker's 'nightly' tag)

on: 
  push:
    branches: # Only run docker deploy, when pushing to my primary branches, not on random pull requests
      - 'main'
      - 'dev'

permissions: {}  

jobs:
  build-workflow:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit
  
  publish-docker-dev:
    name: Publish Nightly Docker Image
    needs: build-workflow
    runs-on: ubuntu-latest
    environment: development
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: docker-artifacts
    - name: Login to DockerHub
      run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PWD}}
    - name: Load & Tag Docker Image
      run: |
        docker load --input ./docker-image.tar.gz
        docker image tag ${{github.event.repository.name}} ${{secrets.DOCKER_USERNAME}}/${{github.event.repository.name}}:nightly
    - name: Push Docker Image
      run: docker image push ${{secrets.DOCKER_USERNAME}}/${{github.event.repository.name}}:nightly