name: Publish Development Release
# This workflow will run on every push against the main or dev branch
# If the app builds and passes tests, it will release to the development channel (Docker's 'nightly' tag)

on: 
  push:
    branches: # Only run dev release, when pushing to the primary branches, ignore pushes with version tag (this indicates a release)
      - 'main'
      - 'dev'
    tags-ignore:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions: {}

env:
  DOCKER_USERNAME: steilerdev

jobs:
  build-workflow:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit
  
  publish-docker-dev:
    name: Publish Nightly Docker Image
    needs: build-workflow
    runs-on: ubuntu-latest
    environment: 
      name: development
      url: https://hub.docker.com/r/steilerdev/icloud-photos-sync
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: docker-artifacts
    - name: Login to DockerHub
      run: docker login -u ${{env.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PWD}}
    - name: Load & Tag Docker Image
      run: |
        docker load --input ./docker-image.tar.gz
        docker image tag ${{github.event.repository.name}} ${{env.DOCKER_USERNAME}}/${{github.event.repository.name}}:nightly
    - name: Push Docker Image
      run: docker image push ${{env.DOCKER_USERNAME}}/${{github.event.repository.name}}:nightly