name: Build & Publish to steilerGroup-Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '17'
    - name: Install dependencies & build app
      run: |
        cd rootfs/opt/icloud-photos-sync/ && \
        npm install && \
        npm run test && \
        npm run build && \
        cd ../../../
    - name: Prepare assets
      run: tar -C ./rootfs -czvf ./rootfs.tar.gz ./
    - name: Upload build
      uses: actions/upload-artifact@v2
      with:
        name: rootfs
        path: ./rootfs.tar.gz
  
  publish:
    name: Publish Project to steilerGroup-Docker
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Download build
      uses: actions/download-artifact@v2
      with:
        name: rootfs
    - name: Login to Docker Registry
      run: docker login docker.steilergroup.net -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PWD}}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.steilergroup.net/$(echo "${{github.repository}}" | awk -F / '{print $2}'):latest
    - name: Push the Docker image
      run: docker push ${{secrets.DOCKER_HOST}}/$(echo "${{github.repository}}" | awk -F / '{print $2}'):latest
