name: Build to steilerGroup-Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '17'
    - name: Install dependencies & build app
      run: |
        cd rootfs/opt/icloud-photos-sync/ && \
        npm install && \
        npm run test && \
        npm run build && \
        cd ../../../
    - name: Prepare assets
      run: tar -C ./rootfs -czvf ./rootfs.tar.gz ./
    - name: Login to Docker Registry
      run: docker login docker.steilergroup.net -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PWD}}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.steilergroup.net/$(echo "${{github.repository}}" | awk -F / '{print $2}'):latest
    - name: Push the Docker image
      run: docker push ${{secrets.DOCKER_HOST}}/$(echo "${{github.repository}}" | awk -F / '{print $2}'):latest
