name: mlflow-operator

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  mlflow-operator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install dependencies
        run: go get .

      - name: Install Operator
        run: make install
        env:
          CB_VERSION: ${{ matrix.version }}

      - name: Run Operator
        run: make run
        env:
          CB_VERSION: ${{ matrix.version }}
